In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

In [2]:
data = pd.read_csv("HouseData.csv")

In [3]:
df = pd.DataFrame(data = data)
df.head()

İlan_Numarası İlan_Güncelleme_Tarihi Kategorisi  Brüt_Metrekare  \
0           2003         02 Şubat 2022    Satılık              190   
1            166          14 Ocak 2022    Satılık              300   
2            167          14 Ocak 2022    Satılık              350   
3            115          06 Ocak 2022    Satılık              450   
4           2879         08 Şubat 2022    Satılık              160   

   Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu Yatırıma_Uygunluk  \
0         5-10                   20       Kiracı Oturuyor        Bilinmiyor    
1  21 Ve Üzeri                    2       Kiracı Oturuyor        Bilinmiyor    
2  21 Ve Üzeri                    3  Mülk Sahibi Oturuyor        Bilinmiyor    
3         5-10                    4       Kiracı Oturuyor        Bilinmiyor    
4  21 Ve Üzeri                    2  Mülk Sahibi Oturuyor        Bilinmiyor    

  Eşya_Durumu Banyo_Sayısı  ... Site_İçerisinde Takas  Fiyat_Durumu    Fiyatı  \
0         Yok           2   ...           Hayır   Var  Genel Fiyat   18000000   
1         Yok           3   ...           Hayır   Var  Genel Fiyat    8500000   
2         Yok           2   ...           Hayır   Var  Genel Fiyat   16500000   
3         Yok           3   ...           Hayır   Var  Genel Fiyat   22000000   
4         Yok           1   ...           Hayır   Var  Genel Fiyat    4250000   

          İl        İlçe                Mahalle           yaka Yaşam_endeksi  \
0  İstanbul    Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası         0.911   
1  İstanbul    Beşiktaş         Akat Mahallesi   Avrupa Yakası         0.911   
2  İstanbul    Beşiktaş       Levent Mahallesi   Avrupa Yakası         0.911   
3  İstanbul    Beşiktaş      Levazım Mahallesi   Avrupa Yakası         0.911   
4  İstanbul    Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası         0.911   

     Nüfus  
0  178.938  
1  178.938  
2  178.938  
3  178.938  
4  178.938  

[5 rows x 27 columns]

In [4]:
drop_columns = ['Brüt_Metrekare', 'İlan_Numarası', 'İlan_Güncelleme_Tarihi', 'Yatırıma_Uygunluk', 'İlan_Oluşturma_Tarihi', 'Site_İçerisinde', 'Takas', 'Fiyat_Durumu', 'Krediye_Uygunluk']
df = df.drop(drop_columns, axis = 1)

In [5]:
df.head()

Kategorisi  Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu  \
0   Satılık          5-10                   20       Kiracı Oturuyor    
1   Satılık   21 Ve Üzeri                    2       Kiracı Oturuyor    
2   Satılık   21 Ve Üzeri                    3  Mülk Sahibi Oturuyor    
3   Satılık          5-10                    4       Kiracı Oturuyor    
4   Satılık   21 Ve Üzeri                    2  Mülk Sahibi Oturuyor    

  Eşya_Durumu Banyo_Sayısı    Türü  Net_Metrekare Oda_Sayısı Bulunduğu_Kat  \
0         Yok           2   Konut             168       4+1        1. Kat    
1         Yok           3   Konut             270       5+1    Bahçe Katı    
2         Yok           2   Konut             320       5+2     Düz Giriş    
3         Yok           3   Konut             400       6+2     Düz Giriş    
4         Yok           1   Konut             140       3+1        1. Kat    

  Isıtma_Tipi    Fiyatı         İl        İlçe                Mahalle  \
0    Klimalı   18000000  İstanbul    Beşiktaş    Nisbetiye Mahallesi    
1    Doğalgaz   8500000  İstanbul    Beşiktaş         Akat Mahallesi    
2    Doğalgaz  16500000  İstanbul    Beşiktaş       Levent Mahallesi    
3    Doğalgaz  22000000  İstanbul    Beşiktaş      Levazım Mahallesi    
4    Doğalgaz   4250000  İstanbul    Beşiktaş    Nisbetiye Mahallesi    

            yaka  Yaşam_endeksi    Nüfus  
0  Avrupa Yakası          0.911  178.938  
1  Avrupa Yakası          0.911  178.938  
2  Avrupa Yakası          0.911  178.938  
3  Avrupa Yakası          0.911  178.938  
4  Avrupa Yakası          0.911  178.938

In [6]:
df['Kategorisi'].unique()

array(['Satılık '], dtype=object)

In [7]:
df['Eşya_Durumu'].unique()

array(['Yok', 'Var'], dtype=object)

In [8]:
df['Türü'].unique()

array(['Konut '], dtype=object)

In [9]:
df['İl'].unique()

array(['İstanbul '], dtype=object)

In [10]:
df['İlçe'].unique()

array([' Beşiktaş ', ' Şişli ', ' Avcılar ', ' Bahçelievler ',
       ' Bakırköy ', ' Başakşehir ', ' Kadıköy ', ' Beylikdüzü ',
       ' Pendik ', ' Esenyurt ', ' Maltepe ', ' Bağcılar ', ' Sarıyer '],
      dtype=object)

In [11]:
df['Mahalle'].unique()

array([' Nisbetiye Mahallesi ', ' Akat Mahallesi ', ' Levent Mahallesi ',
       ' Levazım Mahallesi ', ' Arnavutköy Mahallesi ',
       ' Sinanpaşa Mahallesi ', ' Etiler Mahallesi ',
       ' Yıldız Mahallesi ', ' Dikilitaş Mahallesi ',
       ' Gayrettepe Mahallesi ', ' Ortaköy Mahallesi ',
       ' Mecidiye Mahallesi ', ' Bebek Mahallesi ', ' Türkali Mahallesi ',
       ' Ulus Mahallesi ', ' Abbasağa Mahallesi ',
       ' Cihannüma Mahallesi ', ' Vişnezade Mahallesi ',
       ' Kültür Mahallesi ', ' Muradiye Mahallesi ',
       ' Balmumcu Mahallesi ', ' Kuruçeşme Mahallesi ',
       ' Gümüşpala Mahallesi ', ' Ambarlı Mahallesi ',
       ' Mustafa Kemal Paşa Mahallesi ', ' Üniversite Mahallesi ',
       ' Merkez Mahallesi ', ' Cihangir Mahallesi ',
       ' Denizköşkler Mahallesi ', ' Tahtakale Mahallesi ',
       ' Yeşilkent Mahallesi ', ' Firuzköy Mahallesi ',
       ' Yenibosna Merkez Mahallesi ', ' Zafer Mahallesi ',
       ' Soğanlı Mahallesi ', ' Çobançeşme Mahallesi ',
       

In [12]:
df['yaka'].unique()

array(['Avrupa Yakası', 'Anadolu Yakası'], dtype=object)

In [13]:
df['Yaşam_endeksi'].unique()

array([ 0.911,  0.574, -0.161,  0.053,  0.613, -0.152,  0.886,  0.025,
        0.032, -0.194,  0.161, -0.19 ,  0.347])

In [14]:
df['Nüfus'].unique()

array([178.938, 284.294, 457.981, 605.3  , 228.759, 503.243, 485.233,
       398.122, 741.895, 977.489, 525.566, 744.351, 349.968])

In [15]:
drop_columns = ['Kategorisi', 'Türü', 'İl']
df = df.drop(drop_columns, axis = 1)

In [16]:
df.head()

Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu Eşya_Durumu  \
0         5-10                   20       Kiracı Oturuyor          Yok   
1  21 Ve Üzeri                    2       Kiracı Oturuyor          Yok   
2  21 Ve Üzeri                    3  Mülk Sahibi Oturuyor          Yok   
3         5-10                    4       Kiracı Oturuyor          Yok   
4  21 Ve Üzeri                    2  Mülk Sahibi Oturuyor          Yok   

  Banyo_Sayısı  Net_Metrekare Oda_Sayısı Bulunduğu_Kat Isıtma_Tipi    Fiyatı  \
0           2             168       4+1        1. Kat     Klimalı   18000000   
1           3             270       5+1    Bahçe Katı     Doğalgaz   8500000   
2           2             320       5+2     Düz Giriş     Doğalgaz  16500000   
3           3             400       6+2     Düz Giriş     Doğalgaz  22000000   
4           1             140       3+1        1. Kat     Doğalgaz   4250000   

         İlçe                Mahalle           yaka  Yaşam_endeksi    Nüfus  
0   Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası          0.911  178.938  
1   Beşiktaş         Akat Mahallesi   Avrupa Yakası          0.911  178.938  
2   Beşiktaş       Levent Mahallesi   Avrupa Yakası          0.911  178.938  
3   Beşiktaş      Levazım Mahallesi   Avrupa Yakası          0.911  178.938  
4   Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası          0.911  178.938

In [17]:
df['Binanın_Yaşı'].unique()

array(['5-10 ', '21 Ve Üzeri ', '16-20 ', '0 (Yeni) ', '4 ', '2 ', '1 ',
       '11-15 ', '3 '], dtype=object)

In [18]:
old_mapping = {'5-10 ': 7, '21 Ve Üzeri ': 18, '0 (Yeni) ': 0, '4 ': 4, '2 ': 2, '1 ': 1, '11-15 ': 13, '3 ': 3}
df['Binanın_Yaşı'] = df['Binanın_Yaşı'].map(old_mapping)

In [19]:
df['Kullanım_Durumu'].unique()

array(['Kiracı Oturuyor ', 'Mülk Sahibi Oturuyor ', 'Boş '], dtype=object)

In [20]:
house_using = {'Boş ': 0,'Mülk Sahibi Oturuyor ': 1,'Kiracı Oturuyor ': 2}
df['Kullanım_Durumu'] = df['Kullanım_Durumu'].map(house_using)

In [21]:
df['Eşya_Durumu'].unique()

array(['Yok', 'Var'], dtype=object)

In [22]:
furniture = {'Yok': 0,'Var': 1}
df['Eşya_Durumu'] = df['Eşya_Durumu'].map(furniture)

In [23]:
df['Bulunduğu_Kat'] = pd.factorize(df['Bulunduğu_Kat'])[0]

In [24]:
df['Oda_Sayısı'] = pd.factorize(df['Oda_Sayısı'])[0]

In [25]:
df['Isıtma_Tipi'] = pd.factorize(df['Isıtma_Tipi'])[0]

In [26]:
df['İlçe'] = pd.factorize(df['İlçe'])[0]

In [27]:
df['Mahalle'] = pd.factorize(df['Mahalle'])[0]

In [28]:
df['yaka'] = pd.factorize(df['yaka'])[0]

In [29]:
df.head()

Binanın_Yaşı  Binanın_Kat_Sayısı  Kullanım_Durumu  Eşya_Durumu  \
0           7.0                  20                2            0   
1          18.0                   2                2            0   
2          18.0                   3                1            0   
3           7.0                   4                2            0   
4          18.0                   2                1            0   

  Banyo_Sayısı  Net_Metrekare  Oda_Sayısı  Bulunduğu_Kat  Isıtma_Tipi  \
0           2             168           0              0            0   
1           3             270           1              1            1   
2           2             320           2              2            1   
3           3             400           3              2            1   
4           1             140           4              0            1   

     Fiyatı  İlçe  Mahalle  yaka  Yaşam_endeksi    Nüfus  
0  18000000     0        0     0          0.911  178.938  
1   8500000     0        1     0          0.911  178.938  
2  16500000     0        2     0          0.911  178.938  
3  22000000     0        3     0          0.911  178.938  
4   4250000     0        0     0          0.911  178.938

In [30]:
df['Nüfus'].unique()

array([178.938, 284.294, 457.981, 605.3  , 228.759, 503.243, 485.233,
       398.122, 741.895, 977.489, 525.566, 744.351, 349.968])

In [31]:
print(df)

      Binanın_Yaşı  Binanın_Kat_Sayısı  Kullanım_Durumu  Eşya_Durumu  \
0              7.0                  20                2            0   
1             18.0                   2                2            0   
2             18.0                   3                1            0   
3              7.0                   4                2            0   
4             18.0                   2                1            0   
...            ...                 ...              ...          ...   
2978          18.0                   4                2            0   
2979           NaN                   4                2            0   
2980           NaN                   4                2            0   
2981          18.0                   3                1            0   
2982           7.0                   2                2            0   

     Banyo_Sayısı  Net_Metrekare  Oda_Sayısı  Bulunduğu_Kat  Isıtma_Tipi  \
0              2             168           0              0

In [32]:
#NaN olarak kalan degerler duzeltilecek ve ardindan veriler olceklendirilecek

In [ ]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

# Ölçeklendirilmiş veriyi yeni bir DataFrame'e dönüştür
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)