In [206]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [207]:
data = pd.read_csv("HouseData.csv")

In [208]:
df = pd.DataFrame(data = data)
df.head()

İlan_Numarası İlan_Güncelleme_Tarihi Kategorisi  Brüt_Metrekare  \
0           2003         02 Şubat 2022    Satılık              190   
1            166          14 Ocak 2022    Satılık              300   
2            167          14 Ocak 2022    Satılık              350   
3            115          06 Ocak 2022    Satılık              450   
4           2879         08 Şubat 2022    Satılık              160   

   Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu Yatırıma_Uygunluk  \
0         5-10                   20       Kiracı Oturuyor        Bilinmiyor    
1  21 Ve Üzeri                    2       Kiracı Oturuyor        Bilinmiyor    
2  21 Ve Üzeri                    3  Mülk Sahibi Oturuyor        Bilinmiyor    
3         5-10                    4       Kiracı Oturuyor        Bilinmiyor    
4  21 Ve Üzeri                    2  Mülk Sahibi Oturuyor        Bilinmiyor    

  Eşya_Durumu Banyo_Sayısı  ... Site_İçerisinde Takas  Fiyat_Durumu    Fiyatı  \
0         Yok           2   ...           Hayır   Var  Genel Fiyat   18000000   
1         Yok           3   ...           Hayır   Var  Genel Fiyat    8500000   
2         Yok           2   ...           Hayır   Var  Genel Fiyat   16500000   
3         Yok           3   ...           Hayır   Var  Genel Fiyat   22000000   
4         Yok           1   ...           Hayır   Var  Genel Fiyat    4250000   

          İl        İlçe                Mahalle           yaka Yaşam_endeksi  \
0  İstanbul    Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası         0.911   
1  İstanbul    Beşiktaş         Akat Mahallesi   Avrupa Yakası         0.911   
2  İstanbul    Beşiktaş       Levent Mahallesi   Avrupa Yakası         0.911   
3  İstanbul    Beşiktaş      Levazım Mahallesi   Avrupa Yakası         0.911   
4  İstanbul    Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası         0.911   

     Nüfus  
0  178.938  
1  178.938  
2  178.938  
3  178.938  
4  178.938  

[5 rows x 27 columns]

In [209]:
drop_columns = ['Brüt_Metrekare', 'İlan_Numarası', 'İlan_Güncelleme_Tarihi', 'Yatırıma_Uygunluk', 'İlan_Oluşturma_Tarihi', 'Site_İçerisinde', 'Takas', 'Fiyat_Durumu', 'Krediye_Uygunluk']
df = df.drop(drop_columns, axis = 1)

In [210]:
df.head()

Kategorisi  Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu  \
0   Satılık          5-10                   20       Kiracı Oturuyor    
1   Satılık   21 Ve Üzeri                    2       Kiracı Oturuyor    
2   Satılık   21 Ve Üzeri                    3  Mülk Sahibi Oturuyor    
3   Satılık          5-10                    4       Kiracı Oturuyor    
4   Satılık   21 Ve Üzeri                    2  Mülk Sahibi Oturuyor    

  Eşya_Durumu Banyo_Sayısı    Türü  Net_Metrekare Oda_Sayısı Bulunduğu_Kat  \
0         Yok           2   Konut             168       4+1        1. Kat    
1         Yok           3   Konut             270       5+1    Bahçe Katı    
2         Yok           2   Konut             320       5+2     Düz Giriş    
3         Yok           3   Konut             400       6+2     Düz Giriş    
4         Yok           1   Konut             140       3+1        1. Kat    

  Isıtma_Tipi    Fiyatı         İl        İlçe                Mahalle  \
0    Klimalı   18000000  İstanbul    Beşiktaş    Nisbetiye Mahallesi    
1    Doğalgaz   8500000  İstanbul    Beşiktaş         Akat Mahallesi    
2    Doğalgaz  16500000  İstanbul    Beşiktaş       Levent Mahallesi    
3    Doğalgaz  22000000  İstanbul    Beşiktaş      Levazım Mahallesi    
4    Doğalgaz   4250000  İstanbul    Beşiktaş    Nisbetiye Mahallesi    

            yaka  Yaşam_endeksi    Nüfus  
0  Avrupa Yakası          0.911  178.938  
1  Avrupa Yakası          0.911  178.938  
2  Avrupa Yakası          0.911  178.938  
3  Avrupa Yakası          0.911  178.938  
4  Avrupa Yakası          0.911  178.938

In [211]:
df['Kategorisi'].unique()

array(['Satılık '], dtype=object)

In [212]:
df['Eşya_Durumu'].unique()

array(['Yok', 'Var'], dtype=object)

In [213]:
df['Türü'].unique()

array(['Konut '], dtype=object)

In [214]:
df['İl'].unique()

array(['İstanbul '], dtype=object)

In [215]:
df['İlçe'].unique()

array([' Beşiktaş ', ' Şişli ', ' Avcılar ', ' Bahçelievler ',
       ' Bakırköy ', ' Başakşehir ', ' Kadıköy ', ' Beylikdüzü ',
       ' Pendik ', ' Esenyurt ', ' Maltepe ', ' Bağcılar ', ' Sarıyer '],
      dtype=object)

In [216]:
df['Mahalle'].unique()

array([' Nisbetiye Mahallesi ', ' Akat Mahallesi ', ' Levent Mahallesi ',
       ' Levazım Mahallesi ', ' Arnavutköy Mahallesi ',
       ' Sinanpaşa Mahallesi ', ' Etiler Mahallesi ',
       ' Yıldız Mahallesi ', ' Dikilitaş Mahallesi ',
       ' Gayrettepe Mahallesi ', ' Ortaköy Mahallesi ',
       ' Mecidiye Mahallesi ', ' Bebek Mahallesi ', ' Türkali Mahallesi ',
       ' Ulus Mahallesi ', ' Abbasağa Mahallesi ',
       ' Cihannüma Mahallesi ', ' Vişnezade Mahallesi ',
       ' Kültür Mahallesi ', ' Muradiye Mahallesi ',
       ' Balmumcu Mahallesi ', ' Kuruçeşme Mahallesi ',
       ' Gümüşpala Mahallesi ', ' Ambarlı Mahallesi ',
       ' Mustafa Kemal Paşa Mahallesi ', ' Üniversite Mahallesi ',
       ' Merkez Mahallesi ', ' Cihangir Mahallesi ',
       ' Denizköşkler Mahallesi ', ' Tahtakale Mahallesi ',
       ' Yeşilkent Mahallesi ', ' Firuzköy Mahallesi ',
       ' Yenibosna Merkez Mahallesi ', ' Zafer Mahallesi ',
       ' Soğanlı Mahallesi ', ' Çobançeşme Mahallesi ',
       

In [217]:
df['yaka'].unique()

array(['Avrupa Yakası', 'Anadolu Yakası'], dtype=object)

In [218]:
df['Yaşam_endeksi'].unique()

array([ 0.911,  0.574, -0.161,  0.053,  0.613, -0.152,  0.886,  0.025,
        0.032, -0.194,  0.161, -0.19 ,  0.347])

In [219]:
df['Nüfus'].unique()

array([178.938, 284.294, 457.981, 605.3  , 228.759, 503.243, 485.233,
       398.122, 741.895, 977.489, 525.566, 744.351, 349.968])

In [220]:
drop_columns = ['Kategorisi', 'Türü', 'İl']
df = df.drop(drop_columns, axis = 1)

In [221]:
df.head()

Binanın_Yaşı  Binanın_Kat_Sayısı        Kullanım_Durumu Eşya_Durumu  \
0         5-10                   20       Kiracı Oturuyor          Yok   
1  21 Ve Üzeri                    2       Kiracı Oturuyor          Yok   
2  21 Ve Üzeri                    3  Mülk Sahibi Oturuyor          Yok   
3         5-10                    4       Kiracı Oturuyor          Yok   
4  21 Ve Üzeri                    2  Mülk Sahibi Oturuyor          Yok   

  Banyo_Sayısı  Net_Metrekare Oda_Sayısı Bulunduğu_Kat Isıtma_Tipi    Fiyatı  \
0           2             168       4+1        1. Kat     Klimalı   18000000   
1           3             270       5+1    Bahçe Katı     Doğalgaz   8500000   
2           2             320       5+2     Düz Giriş     Doğalgaz  16500000   
3           3             400       6+2     Düz Giriş     Doğalgaz  22000000   
4           1             140       3+1        1. Kat     Doğalgaz   4250000   

         İlçe                Mahalle           yaka  Yaşam_endeksi    Nüfus  
0   Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası          0.911  178.938  
1   Beşiktaş         Akat Mahallesi   Avrupa Yakası          0.911  178.938  
2   Beşiktaş       Levent Mahallesi   Avrupa Yakası          0.911  178.938  
3   Beşiktaş      Levazım Mahallesi   Avrupa Yakası          0.911  178.938  
4   Beşiktaş    Nisbetiye Mahallesi   Avrupa Yakası          0.911  178.938

In [222]:
df['Binanın_Yaşı'].unique()

array(['5-10 ', '21 Ve Üzeri ', '16-20 ', '0 (Yeni) ', '4 ', '2 ', '1 ',
       '11-15 ', '3 '], dtype=object)

In [223]:
old_mapping = {'5-10 ': 7, '21 Ve Üzeri ': 18, '0 (Yeni) ': 0, '4 ': 4, '2 ': 2, '1 ': 1, '11-15 ': 13, '3 ': 3}
df['Binanın_Yaşı'] = df['Binanın_Yaşı'].map(old_mapping)

In [224]:
df['Kullanım_Durumu'].unique()

array(['Kiracı Oturuyor ', 'Mülk Sahibi Oturuyor ', 'Boş '], dtype=object)

In [225]:
house_using = {'Boş ': 0,'Mülk Sahibi Oturuyor ': 1,'Kiracı Oturuyor ': 2}
df['Kullanım_Durumu'] = df['Kullanım_Durumu'].map(house_using)

In [226]:
df['Eşya_Durumu'].unique()

array(['Yok', 'Var'], dtype=object)

In [227]:
furniture = {'Yok': 0,'Var': 1}
df['Eşya_Durumu'] = df['Eşya_Durumu'].map(furniture)

In [228]:
df['Bulunduğu_Kat'] = pd.factorize(df['Bulunduğu_Kat'])[0]

In [229]:
df['Oda_Sayısı'] = pd.factorize(df['Oda_Sayısı'])[0]

In [230]:
df['Isıtma_Tipi'] = pd.factorize(df['Isıtma_Tipi'])[0]

In [231]:
df['İlçe'] = pd.factorize(df['İlçe'])[0]

In [232]:
df['Mahalle'] = pd.factorize(df['Mahalle'])[0]

In [233]:
df['yaka'] = pd.factorize(df['yaka'])[0]

In [234]:
df['Banyo_Sayısı'] = pd.factorize(df['Banyo_Sayısı'])[0]

In [235]:
df.head()

Binanın_Yaşı  Binanın_Kat_Sayısı  Kullanım_Durumu  Eşya_Durumu  \
0           7.0                  20                2            0   
1          18.0                   2                2            0   
2          18.0                   3                1            0   
3           7.0                   4                2            0   
4          18.0                   2                1            0   

   Banyo_Sayısı  Net_Metrekare  Oda_Sayısı  Bulunduğu_Kat  Isıtma_Tipi  \
0             0            168           0              0            0   
1             1            270           1              1            1   
2             0            320           2              2            1   
3             1            400           3              2            1   
4             2            140           4              0            1   

     Fiyatı  İlçe  Mahalle  yaka  Yaşam_endeksi    Nüfus  
0  18000000     0        0     0          0.911  178.938  
1   8500000     0        1     0          0.911  178.938  
2  16500000     0        2     0          0.911  178.938  
3  22000000     0        3     0          0.911  178.938  
4   4250000     0        0     0          0.911  178.938

In [236]:
df['Nüfus'].unique()

array([178.938, 284.294, 457.981, 605.3  , 228.759, 503.243, 485.233,
       398.122, 741.895, 977.489, 525.566, 744.351, 349.968])

In [237]:
print(df)

      Binanın_Yaşı  Binanın_Kat_Sayısı  Kullanım_Durumu  Eşya_Durumu  \
0              7.0                  20                2            0   
1             18.0                   2                2            0   
2             18.0                   3                1            0   
3              7.0                   4                2            0   
4             18.0                   2                1            0   
...            ...                 ...              ...          ...   
2978          18.0                   4                2            0   
2979           NaN                   4                2            0   
2980           NaN                   4                2            0   
2981          18.0                   3                1            0   
2982           7.0                   2                2            0   

      Banyo_Sayısı  Net_Metrekare  Oda_Sayısı  Bulunduğu_Kat  Isıtma_Tipi  \
0                0            168           0             

In [238]:
#NaN olarak kalan degerler duzeltilecek ve ardindan veriler olceklendirilecek
print(df.isnull().sum())

Binanın_Yaşı          71
Binanın_Kat_Sayısı     0
Kullanım_Durumu        0
Eşya_Durumu            0
Banyo_Sayısı           0
Net_Metrekare          0
Oda_Sayısı             0
Bulunduğu_Kat          0
Isıtma_Tipi            0
Fiyatı                 0
İlçe                   0
Mahalle                0
yaka                   0
Yaşam_endeksi          0
Nüfus                  0
dtype: int64


In [239]:
df = df.dropna()

In [240]:
df.iloc[:, 0]

0        7.0
1       18.0
2       18.0
3        7.0
4       18.0
        ... 
2975     1.0
2977     3.0
2978    18.0
2981    18.0
2982     7.0
Name: Binanın_Yaşı, Length: 2912, dtype: float64

In [241]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(df)

# Ölçeklendirilmiş veriyi yeni bir DataFrame'e dönüştür
scaled_df = pd.DataFrame(scaled_data, columns=df.columns)

In [242]:
df.head()

Binanın_Yaşı  Binanın_Kat_Sayısı  Kullanım_Durumu  Eşya_Durumu  \
0           7.0                  20                2            0   
1          18.0                   2                2            0   
2          18.0                   3                1            0   
3           7.0                   4                2            0   
4          18.0                   2                1            0   

   Banyo_Sayısı  Net_Metrekare  Oda_Sayısı  Bulunduğu_Kat  Isıtma_Tipi  \
0             0            168           0              0            0   
1             1            270           1              1            1   
2             0            320           2              2            1   
3             1            400           3              2            1   
4             2            140           4              0            1   

     Fiyatı  İlçe  Mahalle  yaka  Yaşam_endeksi    Nüfus  
0  18000000     0        0     0          0.911  178.938  
1   8500000     0        1     0          0.911  178.938  
2  16500000     0        2     0          0.911  178.938  
3  22000000     0        3     0          0.911  178.938  
4   4250000     0        0     0          0.911  178.938

In [243]:
X = df.drop('Fiyatı',axis=1)
Y = df['Fiyatı']

In [244]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,train_size=0.2,random_state=42)

In [245]:
logisticModel = LogisticRegression()

In [246]:
logisticModel.fit(x_train,y_train)

/home/esti002/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [247]:
y_pred = logisticModel.predict(x_test)

In [248]:
accurary = accuracy_score(y_test,y_pred)
print(accurary)

0.01587982832618026


In [ ]:
#bazi verilerin silinmesi ya da mapping yapilmis olan verilerin daha onemli verileri kategorize edecek sekilde ayarlanmasi yapimalidir